name: example-go-project-on-pr

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'example-go-project/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  set-up-image-matrix:
    runs-on: ubuntu-latest
    outputs:
      image_matrix: ${{ steps.get-image-names.outputs.image_matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: get image names
        id: get-image-names
        working-directory: ./example-go-project/build/dockerfile
        run: |
          image_matrix='[ '
          for image_name in Dockerfile.*; do
            image_matrix+="\"${image_name##*.}\", "
          done
          image_matrix="${image_matrix%??} ]"
          echo $image_matrix
          echo "image_matrix=$image_matrix" >> $GITHUB_OUTPUT

  build-and-push-images:
    runs-on: ubuntu-latest
    needs: set-up-image-matrix
    strategy:
      matrix:
        image: ${{ fromJson(needs.set-up-image-matrix.outputs.image_matrix) }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build the docker image
        working-directory: ./example-go-project
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/${{matrix.image}}:${GITHUB_SHA:7} -f build/dockerfile/Dockerfile.${{matrix.image}} .

      - name: Push the image
        working-directory: ./example-go-project
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/${{matrix.image}}:${GITHUB_SHA:7}
