name: example-go-project-on-pr

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'example-go-project/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-image-names:
    runs-on: ubuntu-latest
    outputs:
      image_names: ${{ steps.get-image-names.outputs.image_names }}
    steps:
      - name: get image names
        id: get-image-names
        working-directory: ./example-go-project/build/dockerfile
        run: |
          echo "image_names=abc" >> $GITHUB_OUTPUT


  echo-previous-output:
    runs-on: ubuntu-latest
    steps:
      - name: echo job output
        run: echo "666 ${{ needs.get-image-names.outputs.image_names }}"