name: first-project

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'first-project/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-app:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build the docker image
        working-directory: ./first-project
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/first-app:staging-${GITHUB_SHA:7} -f cmd/first-app/Dockerfile .

      - name: Push the image
        working-directory: ./first-project
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/first-app:staging-${GITHUB_SHA:7}
