name: on-comment-created

on:
  issue_comment:
    types:
      - created

jobs:
  read-comment:
    runs-on: ubuntu-latest
    outputs:
      comment-in-json: ${{ steps.read-yq.outputs.comment-in-json }}
    steps:
      - name: $github
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: read yq
        id: read-yq
        run: echo "comment-in-json=$(echo ${{ github.event.comment.body }} | yq - -o=json -I=0)" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: read-comment
    steps:
      - run: echo ${{ needs.read-comment.outputs.comment-in-json }}
